(() => {
  const browserApi=globalThis.browser??globalThis.chrome;
  const SOURCE="personal-social-video-downloader", PORTAL="pvd-overlay-portal", BUTTON="pvd-overlay-button", MENU="pvd-quality-menu";
  const entries=new Map(); let frameQueued=false;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  async function send(m){if(!browserApi?.runtime?.sendMessage)throw new Error("Eklenti arka plan servisine erişilemiyor.");return await browserApi.runtime.sendMessage(m);}
  function platform(){return location.hostname.includes("instagram.com")?"instagram":"x";}
  function twKey(url=""){const m=String(url).match(/\/(?:ext_tw_video(?:_thumb)?|ext_tw_video|amplify_video(?:_thumb)?|amplify_video|tweet_video(?:_thumb)?|tweet_video)\/(\d+)/i);return m?m[1]:null;}
  function visible(v){if(!(v instanceof HTMLVideoElement)||!v.isConnected)return false;const r=v.getBoundingClientRect(),s=getComputedStyle(v);return r.width>=150&&r.height>=100&&r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth&&s.display!=="none"&&s.visibility!=="hidden";}
  function xData(v){const scope=v.closest('article[data-testid="tweet"]')||v.closest("article")||v.parentElement||document.body;for(const a of scope.querySelectorAll('a[href*="/status/"]')){try{const m=new URL(a.href,location.href).pathname.match(/^\/([^/]+)\/status\/(\d+)/);if(m)return {username:m[1],tweetId:m[2]}}catch{}}const m=location.pathname.match(/^\/([^/]+)\/status\/(\d+)/);return m?{username:m[1],tweetId:m[2]}:{username:"x_user",tweetId:"video"};}
  function igData(v){let m=location.pathname.match(/^\/stories\/([^/]+)\/(\d+)/i);if(m)return {username:m[1],postKey:`story:${m[2]}`,contentKind:"story"};m=location.pathname.match(/^\/(?:reel|reels|p)\/([^/]+)/i);let key=m?m[1]:null,kind=m?(location.pathname.includes("reel")?"reel":"post"):"feed",username="instagram";let node=v.parentElement,depth=0;while(node&&node!==document.body&&depth++<14){for(const a of node.querySelectorAll('a[href]')){try{const u=new URL(a.href,location.href),pm=u.pathname.match(/^\/(?:reel|reels|p)\/([^/]+)/i),um=u.pathname.match(/^\/([^/]+)\/$/);if(!key&&pm)key=pm[1];if(um&&!['accounts','direct','explore','reel','reels','p','stories','about','legal','web'].includes(um[1].toLowerCase()))username=um[1]}catch{}}node=node.parentElement;}return {username,postKey:key,contentKind:kind};}
  function requestData(v){const direct=[v.currentSrc,v.src].find(u=>typeof u==="string"&&/^https?:/i.test(u)&&!u.startsWith("blob:"))||null;if(platform()==="x"){const d=xData(v),urls=[v.currentSrc,v.src,v.poster].filter(Boolean);let key=null;for(const u of urls){key=twKey(u);if(key)break}return {platform:"x",...d,mediaKey:key,directUrl:direct}}return {platform:"instagram",...igData(v),directUrl:direct};}
  function toast(t,k="info"){document.querySelector(".pvd-toast")?.remove();const e=document.createElement("div");e.className=`pvd-toast pvd-toast-${k}`;e.textContent=t;document.documentElement.appendChild(e);requestAnimationFrame(()=>e.classList.add("pvd-toast-show"));setTimeout(()=>{e.classList.remove("pvd-toast-show");setTimeout(()=>e.remove(),180)},2600)}
  function closeMenus(except=null){for(const m of document.querySelectorAll(`.${MENU}`))if(m!==except)m.remove()}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
  function menuShell(portal){closeMenus();const m=document.createElement("div");m.className=MENU;m.innerHTML='<div class="pvd-menu-head"><div><strong>İndirme</strong><span>Temiz kaynak • yerel işlem</span></div></div><div class="pvd-menu-body"><div class="pvd-loading"><i></i><span>Kaliteler aranıyor…</span></div></div>';portal.appendChild(m);requestAnimationFrame(()=>m.classList.add("pvd-quality-menu-show"));return m;}
  function errorMenu(menu,msg,v){const body=menu.querySelector('.pvd-menu-body');body.innerHTML=`<div class="pvd-menu-error">${esc(msg)}</div><button class="pvd-menu-retry" type="button">Tekrar Dene</button>`;body.querySelector('.pvd-menu-retry').dataset.pvdRetry='1';body.querySelector('.pvd-menu-retry').__pvdVideo=v;}
  function renderOptions(menu,v,button,variants){const body=menu.querySelector('.pvd-menu-body');body.innerHTML='';for(const q of variants){const o=document.createElement('button');o.type='button';o.className='pvd-quality-option';o.__pvdVariant=q;o.__pvdVideo=v;o.__pvdButton=button;o.innerHTML=`<span><b>${esc(q.label)}</b>${q.best?'<em>EN İYİ</em>':''}</span><small>${q.width&&q.height?`${q.width}×${q.height}`:'Orijinal medya'}</small>`;body.appendChild(o)}const audio=document.createElement('button');audio.type='button';audio.className='pvd-audio-option';audio.__pvdVideo=v;audio.__pvdButton=button;audio.innerHTML='<span><b>Sadece Ses</b><em>MP3</em></span><small>Yerel dönüştürme</small>';body.appendChild(audio);const note=document.createElement('div');note.className='pvd-clean-note';note.textContent='Platform arayüzü/filigranı eklenmez. Kaynak videoya gömülü işaretler korunur.';body.appendChild(note)}
  async function openMenu(v,button,portal){let existing=portal.querySelector(`.${MENU}`);if(existing){existing.remove();return}const menu=menuShell(portal);window.postMessage({source:SOURCE,type:'RESCAN_REQUEST'},'*');await sleep(120);let r;try{r=await send({type:'GET_VARIANTS',...requestData(v)});if(!r?.ok){await sleep(420);window.postMessage({source:SOURCE,type:'RESCAN_REQUEST'},'*');r=await send({type:'GET_VARIANTS',...requestData(v)})}if(!menu.isConnected)return;if(!r?.ok)errorMenu(menu,r?.message||'Video kaynağı bulunamadı.',v);else renderOptions(menu,v,button,r.variants||[])}catch(e){if(menu.isConnected)errorMenu(menu,e?.message||'Kalite seçenekleri alınamadı.',v)}}
  async function download(v,button,q){closeMenus();button.dataset.state='loading';try{const r=await send({type:'DOWNLOAD_SELECTED',...requestData(v),selectedUrl:q.url});if(r?.ok){button.dataset.state='done';toast(`İndirme başladı${r.quality?` • ${r.quality}`:''}`,'success');setTimeout(()=>button.dataset.state='',1500)}else{button.dataset.state='';toast(r?.message||'Video indirilemedi.','error')}}catch(e){button.dataset.state='';toast(e?.message||'Video indirilemedi.','error')}}
  async function audio(v,button){closeMenus();button.dataset.state='loading';try{const r=await send({type:'EXTRACT_AUDIO',...requestData(v)});button.dataset.state='';if(r?.ok)toast(r.message||'Ses çıkarma başlatıldı.','success');else toast(r?.message||'Ses çıkarılamadı.','error')}catch(e){button.dataset.state='';toast(e?.message||'Ses çıkarılamadı.','error')}}
  function makePortal(v){if(entries.has(v))return;const p=document.createElement('div');p.className=PORTAL;const b=document.createElement('button');b.type='button';b.className=BUTTON;b.innerHTML='<span class="pvd-download-icon">↓</span><span class="pvd-button-label">İndir</span><span class="pvd-chevron">⌄</span>';p.appendChild(b);document.documentElement.appendChild(p);entries.set(v,{v,p,b});}
  function position(){frameQueued=false;for(const [v,e] of [...entries]){if(!v.isConnected){e.p.remove();entries.delete(v);continue}if(!visible(v)){e.p.classList.remove('pvd-overlay-visible');continue}const r=v.getBoundingClientRect();e.p.style.left=`${Math.round(r.right-(r.width<360?8:12))}px`;e.p.style.top=`${Math.round(r.top+(r.height<260?8:12))}px`;e.p.classList.add('pvd-overlay-visible')}}
  function queue(){if(frameQueued)return;frameQueued=true;requestAnimationFrame(position)}
  function scan(){for(const v of document.querySelectorAll('video')){const r=v.getBoundingClientRect();if(r.width&&r.height&&(r.width<150||r.height<100))continue;makePortal(v)}queue()}
  function pathTarget(ev,cls){for(const n of ev.composedPath?.()||[]){if(n instanceof Element&&n.classList?.contains(cls))return n}return null}
  // FIX v1.3.2: handle extension interactions at WINDOW capture. We do not stop
  // the event at document level before it reaches our own button anymore.
  window.addEventListener('click',ev=>{
    const option=pathTarget(ev,'pvd-quality-option');if(option){ev.preventDefault();ev.stopImmediatePropagation();download(option.__pvdVideo,option.__pvdButton,option.__pvdVariant);return}
    const aud=pathTarget(ev,'pvd-audio-option');if(aud){ev.preventDefault();ev.stopImmediatePropagation();audio(aud.__pvdVideo,aud.__pvdButton);return}
    const retry=pathTarget(ev,'pvd-menu-retry');if(retry){ev.preventDefault();ev.stopImmediatePropagation();const entry=entries.get(retry.__pvdVideo);if(entry){retry.closest(`.${MENU}`)?.remove();openMenu(entry.v,entry.b,entry.p)}return}
    const btn=pathTarget(ev,BUTTON);if(btn){ev.preventDefault();ev.stopImmediatePropagation();const entry=[...entries.values()].find(x=>x.b===btn);if(entry)openMenu(entry.v,entry.b,entry.p);return}
    if(!pathTarget(ev,PORTAL))closeMenus();
  },true);
  window.addEventListener('message',e=>{if(e.source!==window||e.data?.source!==SOURCE||e.data?.type!=="MEDIA_VARIANTS"||!Array.isArray(e.data.variants))return;Promise.resolve(send({type:'CACHE_VARIANTS',variants:e.data.variants})).catch(()=>{})});
  document.addEventListener('copy',()=>{setTimeout(async()=>{try{const t=await navigator.clipboard?.readText?.();if(/^https?:\/\/(?:www\.)?(?:x\.com|twitter\.com|instagram\.com)\//i.test(t||''))await browserApi.storage.local.set({pvd_last_clipboard_url:t})}catch{}},0)});
  window.addEventListener('scroll',queue,{passive:true});window.addEventListener('resize',queue,{passive:true});
  const mo=new MutationObserver(scan);function start(){mo.observe(document.documentElement,{childList:true,subtree:true});scan();setInterval(scan,2200)}if(document.documentElement)start();else document.addEventListener('DOMContentLoaded',start,{once:true});
  browserApi.runtime.onMessage.addListener((m,s,respond)=>{if(m?.type==='OPEN_PRIMARY_MENU'){const e=[...entries.values()].find(x=>visible(x.v));if(e){openMenu(e.v,e.b,e.p);respond({ok:true})}else respond({ok:false,message:'Görünür video bulunamadı.'});return} });
})();
